import React, { useEffect, useState } from 'react';

export const RequestsPage = () => {
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [notification, setNotification] = useState(null);
  
  // États pour la notation et signalement
  const [selectedRequestForRating, setSelectedRequestForRating] = useState(null);
  const [showReportModal, setShowReportModal] = useState(null);
  const [showCancelModal, setShowCancelModal] = useState(null);
  const [rating, setRating] = useState(0);
  const [comment, setComment] = useState("");
  const [reportReason, setReportReason] = useState("non_rendu");
  const [reportDescription, setReportDescription] = useState("");

  const [currentUser] = useState(() => {
    const savedUser = localStorage.getItem('user');
    return savedUser ? JSON.parse(savedUser) : { id: null, name: "Invité", role: 'emprunteur' };
  });

  useEffect(() => {
    fetchRequests();
  }, [currentUser]);

  const fetchRequests = async () => {
    try {
      let url = currentUser.role === 'preteur' 
        ? `http://localhost:5000/requests?ownerName=${currentUser.name}`
        : `http://localhost:5000/requests?requesterId=${currentUser.id}`;
      
      const response = await fetch(url);
      const data = await response.json();
      setRequests(data);
      setLoading(false);
    } catch (error) {
      setLoading(false);
    }
  };

  // US-04 : Accepter avec calcul automatique de date de retour (J+15)
  const handleStatusChange = async (request, newStatus) => {
    try {
      const updates = { status: newStatus };

      if (newStatus === 'accepted') {
        const returnDate = new Date();
        returnDate.setDate(returnDate.getDate() + 15);
        updates.returnDate = returnDate.toISOString().split('T')[0];
        updates.isFinished = false;
        updates.reminderHistory = [];
      }

      const requestResponse = await fetch(
        `http://localhost:5000/requests/${request.id}`,
        {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(updates),
        }
      );

      if (!requestResponse.ok) return;

      if (newStatus === 'accepted') {
        await fetch(`http://localhost:5000/books/${request.bookId}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ status: 'unavailable' }),
        });
      }

      fetchRequests();
      setNotification('Action enregistrée avec succès !');
      setTimeout(() => setNotification(null), 3000);

    } catch (error) {
      console.error('Erreur lors du changement de statut :', error);
    }
  };

  // ====================================================================
  // NOUVELLE FONCTIONNALITÉ : ANNULER UNE DEMANDE (EMPRUNTEUR)
  // ====================================================================
  const handleCancelRequest = async () => {
    try {
      // Supprimer la demande
      const response = await fetch(`http://localhost:5000/requests/${showCancelModal.id}`, {
        method: 'DELETE'
      });

      if (response.ok) {
        setShowCancelModal(null);
        setNotification("✅ Demande annulée avec succès !");
        fetchRequests();
        setTimeout(() => setNotification(null), 3000);
      }
    } catch (error) {
      console.error("Erreur lors de l'annulation:", error);
      setNotification("❌ Erreur lors de l'annulation");
      setTimeout(() => setNotification(null), 3000);
    }
  };

  // ====================================================================
  // TÂCHE 4 : GÉNÉRER LE MESSAGE DE RAPPEL (contenu automatique)
  // ====================================================================
  const generateReminderMessage = (request) => {
    const today = new Date();
    const returnDate = new Date(request.returnDate);
    const diffTime = returnDate - today;
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    let message = `Rappel concernant le livre « ${request.bookTitle} ».`;
    
    if (diffDays < 0) {
      message += ` ⚠️ Attention : le livre aurait dû être rendu il y a ${Math.abs(diffDays)} jour(s). Merci de le restituer dès que possible.`;
    } else if (diffDays === 0) {
      message += ` 📅 Le livre doit être rendu aujourd'hui (${request.returnDate}).`;
    } else {
      message += ` 📅 Date de retour prévue : ${request.returnDate} (dans ${diffDays} jour(s)).`;
    }

    return message;
  };

  // ====================================================================
  // TÂCHE 4 : ENVOYER LE RAPPEL À L'EMPRUNTEUR (notification + email)
  // ====================================================================
  const handleSendReminder = async (request) => {
    const autoGeneratedMessage = generateReminderMessage(request);
    
    const reminderLog = {
      date: new Date().toLocaleString('fr-FR'),
      message: autoGeneratedMessage,
      sentBy: currentUser.name
    };
  
    const reminderHistoryUpdated = [
      ...(request.reminderHistory || []),
      reminderLog
    ];
  
    try {
      console.log('📧 Envoi du rappel à:', request.requesterName);
      
      // ============================================================
      // ÉTAPE 1 : ENVOI RÉEL DU RAPPEL VIA L'API
      // ============================================================
      const sendResponse = await fetch(`http://localhost:5000/notifications/send`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          type: 'reminder',
          recipientId: request.requesterId,
          recipientName: request.requesterName,
          recipientEmail: request.requesterEmail,
          subject: `📚 Rappel : Retour du livre "${request.bookTitle}"`,
          message: autoGeneratedMessage,
          requestId: request.id,
          senderId: currentUser.id,
          senderName: currentUser.name,
          priority: 'high'
        })
      });

      if (!sendResponse.ok) {
        throw new Error("Échec de l'envoi du rappel");
      }

      const sendData = await sendResponse.json();
      console.log('✅ Rappel envoyé avec succès:', sendData);

      // ============================================================
      // ÉTAPE 2 : ENREGISTREMENT DANS L'HISTORIQUE
      // ============================================================
      const response = await fetch(`http://localhost:5000/requests/${request.id}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ reminderHistory: reminderHistoryUpdated })
      });
  
      if (response.ok) {
        setNotification(`🔔 Rappel envoyé avec succès à ${request.requesterName} par notification et email !`);
        fetchRequests();
        setTimeout(() => setNotification(null), 3000);
      }
    } catch (error) {
      console.error("Erreur lors de l'envoi du rappel :", error);
      setNotification("❌ Erreur lors de l'envoi du rappel. Réessayez.");
      setTimeout(() => setNotification(null), 3000);
    }
  };
  
  const handleConfirmReturn = async (req) => {
    try {
      await fetch(`http://localhost:5000/requests/${req.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isFinished: true })
      });

      await fetch(`http://localhost:5000/books/${req.bookId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'available' })
      });

      setNotification("✅ Livre récupéré ! L'échange est clos.");
      fetchRequests();
      setTimeout(() => setNotification(null), 3000);
    } catch (error) {
      console.error("Erreur retour:", error);
    }
  };

  // ====================================================================
  // TÂCHE 1 : ENREGISTRER LA NOTE ET LE COMMENTAIRE
  // ====================================================================
  const submitRating = async () => {
  // Validation de la notation
  if (rating === 0) {
    setNotification("⚠️ Veuillez sélectionner au moins une étoile");
    setTimeout(() => setNotification(null), 3000);
    return;
  }

  try {
    // Préparation des données de notation
    const ratingData = {
      rating: rating,
      comment: comment,
      ratedBy: currentUser.name,
      ratedAt: new Date().toISOString(),
      requestId: selectedRequestForRating.id
    };

    // Envoi de la notation au serveur
    const response = await fetch(`http://localhost:5000/requests/${selectedRequestForRating.id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        userRating: ratingData,
        hasBeenRated: true
      })
    });

    // Vérification de la réponse
    if (response.ok) {
      console.log("✅ Notation enregistrée avec succès", ratingData);
        // ============================================================
        // TÂCHE 2 : METTRE À JOUR LA NOTE MOYENNE DE L'UTILISATEUR
        // ============================================================
        try {
          // Déterminer qui doit recevoir cette note
          const ratedUserId = currentUser.role === 'preteur' 
            ? selectedRequestForRating.requesterId 
            : selectedRequestForRating.ownerId;

          // Recalculer la note moyenne de cet utilisateur
          const ratingResponse = await fetch(`http://localhost:5000/users/${ratedUserId}/rating`);
          const ratingStats = await ratingResponse.json();

          // Mettre à jour le profil de l'utilisateur avec sa nouvelle note
          await fetch(`http://localhost:5000/users/${ratedUserId}/rating`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              averageRating: ratingStats.averageRating,
              totalRatings: ratingStats.totalRatings
            })
          });

          console.log(`✅ Note moyenne mise à jour pour l'utilisateur ${ratedUserId}:`, ratingStats.averageRating);
        } catch (error) {
          console.warn("⚠️ Note enregistrée mais moyenne non calculée:", error);
        }

        setSelectedRequestForRating(null);
        setRating(0);
        setComment("");
        
        setNotification("⭐ Merci pour votre avis ! Il a été enregistré.");
        setTimeout(() => setNotification(null), 3000);
        
        fetchRequests();
      }
    } catch (error) {
      console.error("❌ Erreur lors de l'enregistrement de la notation:", error);
      setNotification("❌ Erreur lors de l'enregistrement. Réessayez.");
      setTimeout(() => setNotification(null), 3000);
    }
  };

  // ====================================================================
  // TÂCHE 2 & 3 : ENREGISTRER LE SIGNALEMENT + NOTIFIER L'ADMIN
  // ====================================================================
  const handleSubmitReport = async () => {
    if (!reportDescription.trim()) {
      setNotification("⚠️ Veuillez décrire l'incident");
      setTimeout(() => setNotification(null), 3000);
      return;
    }

    try {
      const reportData = {
        requestId: showReportModal.id,
        bookId: showReportModal.bookId,
        bookTitle: showReportModal.bookTitle,
        reportedBy: currentUser.name,
        reportedByUserId: currentUser.id,
        reportedByRole: currentUser.role,
        targetUser: currentUser.role === 'preteur' ? showReportModal.requesterName : showReportModal.ownerName,
        targetUserId: currentUser.role === 'preteur' ? showReportModal.requesterId : showReportModal.ownerId,
        reason: reportReason,
        description: reportDescription,
        status: "en_attente",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      console.log("📤 Envoi du signalement:", reportData);

      // ============================================================
      // ÉTAPE 1 : ENVOI DU SIGNALEMENT (NOTIFIE AUTO LES ADMINS)
      // ============================================================
      const reportResponse = await fetch(`http://localhost:5000/reports`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify(reportData)
      });

      if (!reportResponse.ok) {
        const errorText = await reportResponse.text();
        console.error("❌ Erreur serveur:", errorText);
        throw new Error(`Erreur serveur: ${reportResponse.status}`);
      }

      const savedReport = await reportResponse.json();
      console.log("✅ Signalement enregistré:", savedReport);
      
      // Le backend a automatiquement notifié les admins
      if (savedReport.adminsNotified) {
        console.log(`✅ ${savedReport.adminsNotified} administrateur(s) notifié(s)`);
      }

      // ============================================================
      // ÉTAPE 2 : MISE À JOUR DE LA DEMANDE
      // ============================================================
      const updateResponse = await fetch(`http://localhost:5000/requests/${showReportModal.id}`, {
        method: 'PATCH',
        headers: { 
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify({ 
          hasReport: true,
          reportStatus: "en_attente",
          reportId: savedReport.report.id
        })
      });

      if (!updateResponse.ok) {
        console.error("❌ Erreur mise à jour de la demande");
      }

      // ============================================================
      // CONFIRMATION
      // ============================================================
      setShowReportModal(null);
      setReportReason("non_rendu");
      setReportDescription("");
      
      setNotification(`✅ Signalement enregistré et ${savedReport.adminsNotified || 0} admin(s) notifié(s) !`);
      setTimeout(() => setNotification(null), 3000);
      
      fetchRequests();

    } catch (error) {
      console.error("❌ Erreur complète lors de l'enregistrement du signalement:", error);
      setNotification(`❌ Erreur: ${error.message}. Vérifiez que le serveur est démarré.`);
      setTimeout(() => setNotification(null), 5000);
    }
  };

  if (loading) return <div className="p-10 text-center font-bold text-gray-400 dark:text-gray-500 italic">Chargement...</div>;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 relative transition-colors duration-200">
      {notification && (
        <div className="fixed top-5 left-1/2 -translate-x-1/2 bg-indigo-600 dark:bg-indigo-500 text-white px-8 py-4 rounded-2xl shadow-2xl z-50 font-bold animate-bounce">
          {notification}
        </div>
      )}

      <div className="max-w-6xl mx-auto">
        <h1 className="text-3xl font-black text-gray-900 dark:text-gray-100 mb-8 tracking-tight italic uppercase transition-colors">Gestion des Échanges</h1>

        <div className="bg-white dark:bg-gray-800 rounded-3xl shadow-xl border border-gray-100 dark:border-gray-700 overflow-hidden transition-colors">
          <table className="w-full text-left border-collapse">
            <thead className="bg-gray-50 dark:bg-gray-700 border-b border-gray-100 dark:border-gray-600 transition-colors">
              <tr>
                <th className="p-5 font-bold text-gray-400 dark:text-gray-300 uppercase text-xs tracking-widest">Livre & Échéance</th>
                <th className="p-5 font-bold text-gray-400 dark:text-gray-300 uppercase text-xs tracking-widest">Partenaire</th>
                <th className="p-5 font-bold text-gray-400 dark:text-gray-300 uppercase text-xs tracking-widest text-center">Historique Rappels</th>
                <th className="p-5 font-bold text-gray-400 dark:text-gray-300 uppercase text-xs tracking-widest text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50 dark:divide-gray-700">
              {requests.map((req) => (
                <tr key={req.id} className="hover:bg-indigo-50/20 dark:hover:bg-indigo-900/10 transition-colors">
                  <td className="p-5">
                    <span className="font-bold text-gray-900 dark:text-gray-100 block">📖 {req.bookTitle}</span>
                    {req.status === 'accepted' && req.returnDate && (
                      <span className={`text-[9px] font-black px-2 py-0.5 rounded uppercase ${new Date(req.returnDate) < new Date() ? 'bg-red-100 dark:bg-red-900 text-red-600 dark:text-red-400' : 'bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-400'}`}>
                        {new Date(req.returnDate) < new Date() ? '⚠️ Retard' : 'Retour'} : {req.returnDate}
                      </span>
                    )}
                    {req.hasReport && (
                      <span className={`ml-2 text-[9px] font-black px-2 py-0.5 rounded uppercase ${
                        req.reportStatus === 'resolu' ? 'bg-green-100 dark:bg-green-900 text-green-600 dark:text-green-400' :
                        req.reportStatus === 'traite' ? 'bg-orange-100 dark:bg-orange-900 text-orange-600 dark:text-orange-400' :
                        'bg-red-100 dark:bg-red-900 text-red-600 dark:text-red-400'
                      }`}>
                        🚨 {req.reportStatus === 'en_attente' ? 'Signalé' : 
                            req.reportStatus === 'traite' ? 'En cours' : 'Résolu'}
                      </span>
                    )}
                  </td>
                  <td className="p-5 text-gray-600 dark:text-gray-400 font-medium">
                    {currentUser.role === 'preteur' ? req.requesterName : req.ownerName}
                  </td>
                  <td className="p-5 text-center">
                    {req.reminderHistory?.length > 0 ? (
                      <div className="group relative inline-block">
                        <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 cursor-help bg-indigo-50 dark:bg-indigo-900/30 px-2 py-1 rounded-lg">
                          {req.reminderHistory.length} rappel(s)
                        </span>
                        <div className="hidden group-hover:block absolute z-10 bg-gray-900 dark:bg-gray-800 text-white text-[10px] p-3 rounded shadow-lg w-64 -left-20 mt-1">
                          {req.reminderHistory.map((h, i) => (
                            <div key={i} className="mb-2 pb-2 border-b border-gray-700 dark:border-gray-600 last:border-0">
                              <div className="font-bold text-yellow-400">{h.date}</div>
                              <div className="mt-1">{h.message}</div>
                            </div>
                          ))}
                        </div>
                      </div>
                    ) : (
                      <span className="text-gray-300 dark:text-gray-600 text-xs">---</span>
                    )}
                  </td>
                  <td className="p-5 text-right flex justify-end gap-3 items-center">
                    
                    {/* ============================================================
                        NOUVEAU : BOUTON ANNULER POUR L'EMPRUNTEUR
                        ============================================================ */}
                    {currentUser.role === 'emprunteur' && req.status === 'pending' && (
                      <button 
                        onClick={() => setShowCancelModal(req)} 
                        className="bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 border border-red-200 dark:border-red-800 px-3 py-1.5 rounded-xl text-xs font-bold hover:bg-red-100 dark:hover:bg-red-900/50 transition"
                      >
                        ❌ Annuler
                      </button>
                    )}

                    {req.status === 'accepted' && !req.isFinished && currentUser.role === 'preteur' && (
                      <button 
                        onClick={() => handleSendReminder(req)} 
                        className="text-indigo-600 dark:text-indigo-400 hover:scale-125 transition text-xl" 
                        title="Relancer l'emprunteur"
                      >
                        🔔
                      </button>
                    )}

                    {currentUser.role === 'preteur' && req.status === 'pending' ? (
                      <div className="flex gap-2">
                        <button onClick={() => handleStatusChange(req, 'accepted')} className="bg-green-600 dark:bg-green-700 text-white px-3 py-1.5 rounded-xl text-xs font-bold shadow-md">Accepter</button>
                        <button onClick={() => handleStatusChange(req, 'rejected')} className="bg-white dark:bg-gray-700 text-red-600 dark:text-red-400 border border-red-100 dark:border-red-800 px-3 py-1.5 rounded-xl text-xs font-bold">Refuser</button>
                      </div>
                    ) : (
                      req.status === 'accepted' && (
                        req.isFinished ? (
                          !req.hasBeenRated && (
                            <button onClick={() => setSelectedRequestForRating(req)} className="bg-amber-400 dark:bg-amber-500 text-white px-3 py-1.5 rounded-xl text-xs font-bold shadow-lg shadow-amber-100 dark:shadow-amber-900/30">⭐ Noter</button>
                          )
                        ) : (
                          currentUser.role === 'preteur' && (
                            <button onClick={() => handleConfirmReturn(req)} className="bg-indigo-600 dark:bg-indigo-500 text-white px-3 py-1.5 rounded-xl text-xs font-bold">Confirmer Retour</button>
                          )
                        )
                      )
                    )}

                    <button onClick={() => setShowReportModal(req)} className="text-gray-300 dark:text-gray-600 hover:text-red-500 dark:hover:text-red-400 text-[10px] font-black uppercase transition">Signaler</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* ============================================================
          NOUVELLE MODAL : CONFIRMATION D'ANNULATION
          ============================================================ */}
      {showCancelModal && (
        <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="w-full max-w-md bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-2xl transition-colors">
            <h2 className="mb-4 text-xl font-black text-red-600 dark:text-red-400 uppercase tracking-tighter">
              ❌ Annuler la demande ?
            </h2>

            <p className="text-sm text-gray-600 dark:text-gray-400 mb-6 font-medium">
              Êtes-vous sûr de vouloir annuler votre demande pour "<span className="font-bold text-gray-900 dark:text-gray-100">{showCancelModal.bookTitle}</span>" ?
            </p>

            <div className="flex gap-4">
              <button
                onClick={() => setShowCancelModal(null)}
                className="flex-1 py-4 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-2xl font-bold hover:bg-gray-200 dark:hover:bg-gray-600 transition"
              >
                Non, garder
              </button>

              <button
                onClick={handleCancelRequest}
                className="flex-1 py-4 bg-red-600 dark:bg-red-500 text-white rounded-2xl font-bold hover:bg-red-700 dark:hover:bg-red-600 transition"
              >
                Oui, annuler
              </button>
            </div>
          </div>
        </div>
      )}

   {/* MODALE DE SIGNALEMENT */}
   {showReportModal && (
     <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
       <div className="w-full max-w-md bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-2xl transition-colors">
         
         <h2 className="mb-4 text-xl font-black text-rose-600 dark:text-rose-400 uppercase tracking-tighter">
           🚨 Déclarer un incident
         </h2>

         <p className="text-xs text-gray-500 dark:text-gray-400 mb-4 font-medium">
           Votre signalement sera enregistré et les administrateurs seront notifiés automatiquement.
         </p>

         <select
           value={reportReason}
           onChange={(e) => setReportReason(e.target.value)}
           className="w-full mb-4 p-4 rounded-xl bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold outline-none appearance-none"
         >
           <option value="non_rendu">📕 Livre non restitué</option>
           <option value="abime">💔 Livre détérioré</option>
           <option value="absence">👻 Rendez-vous manqué</option>
           <option value="comportement">⚠️ Comportement inapproprié</option>
         </select>

         <textarea
           value={reportDescription}
           onChange={(e) => setReportDescription(e.target.value)}
           placeholder="Décrivez brièvement la situation... (obligatoire)"
           className="w-full h-32 mb-4 p-4 rounded-2xl bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100 text-sm font-medium outline-none border-2 border-transparent focus:border-rose-300 dark:focus:border-rose-500"
         />

         <div className="flex gap-4">
           <button
             onClick={() => {
               setShowReportModal(null);
               setReportDescription("");
             }}
             className="flex-1 font-bold text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300"
           >
             Annuler
           </button>

           <button
             onClick={handleSubmitReport}
             className="flex-[2] rounded-2xl bg-rose-600 dark:bg-rose-700 py-4 text-xs font-black uppercase text-white hover:bg-rose-700 dark:hover:bg-rose-800 transition"
           >
             Confirmer le signalement
           </button>
         </div>

       </div>
     </div>
   )}

      {/* MODAL NOTATION */}
      {selectedRequestForRating && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-[60] flex items-center justify-center p-4">
          <div className="bg-white dark:bg-gray-800 rounded-3xl p-8 max-w-md w-full shadow-2xl transition-colors">
            <h2 className="text-2xl font-black text-gray-900 dark:text-gray-100 mb-2">Avis sur l'échange</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6 font-medium">
              Votre note sera enregistrée et le profil de l'utilisateur sera mis à jour
            </p>
            
            <div className="flex justify-center gap-3 mb-6">
              {[1, 2, 3, 4, 5].map((star) => (
                <button 
                  key={star} 
                  onClick={() => setRating(star)} 
                  className={`text-4xl transition-all hover:scale-110 ${rating >= star ? 'text-yellow-400' : 'text-gray-200 dark:text-gray-600'}`}
                >
                  ★
                </button>
              ))}
            </div>

            <textarea 
              value={comment}
              placeholder="Votre commentaire (optionnel)..." 
              className="w-full bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100 border-none rounded-2xl p-4 h-32 outline-none text-sm font-medium" 
              onChange={(e) => setComment(e.target.value)} 
            />
            
            <div className="flex gap-4 mt-8">
              <button 
                onClick={() => {
                  setSelectedRequestForRating(null);
                  setRating(0);
                  setComment("");
                }} 
                className="flex-1 py-3 text-gray-400 dark:text-gray-500 font-bold hover:text-gray-600 dark:hover:text-gray-300"
              >
                Annuler
              </button>
              <button 
                onClick={submitRating} 
                className="flex-[2] bg-indigo-600 dark:bg-indigo-500 text-white py-4 rounded-2xl font-black uppercase text-xs hover:bg-indigo-700 dark:hover:bg-indigo-600 transition"
              >
                Enregistrer la note
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};